---
title: "p8105_hw2_nl2835"
author: "Nancy Le"
date: 09-28-2023
output: github_document
---

Import FiveThirtyEight data

```{r}
library(tidyverse)

pols_month_df = 
  read_csv(file = 
      "./fivethirtyeight_datasets/pols-month.csv")

```

```{r}
pols_month_df = separate(pols_month_df, col = mon, into = 
         c("Year", "Month", "Day"), sep = "-") 

```

Review column names in pols month df, and separate date variable into month, year, and day. 

```{r}
pols_month_df[["Month"]] <-
  as.numeric(pols_month_df[["Month"]])

```

```{r}
pols_month_df = pols_month_df |> 
  mutate(Month = month.abb[Month])
```

Changed "Month" variable to text.

```{r}
pols_month_df = pols_month_df |> 
  mutate(prez = ifelse(prez_gop=="1", "gop", "dem")) |> 
  select(-prez_gop, -prez_dem, -Day)  
```

Created "prez" variable for presidential party.

```{r}
select(pols_month_df, Year, Month, everything())
```

Reorganized dataset to have year and month as leading columns.

```{r}
SNP_df = 
  read_csv(file = 
      "./fivethirtyeight_datasets/snp.csv") |> 
  separate(col = date, into = 
         c("Month", "Day", "Year"), sep = "/") 
```


```{r}
SNP_df[["Month"]] <-
      as.numeric(SNP_df[["Month"]])

```

```{r}
SNP_df = SNP_df |> 
  mutate(Month = month.abb[Month])
```

```{r}
SNP_df = SNP_df |> 
  mutate(Year = sprintf('20%s', Year)) |> 
  select(Year, Month, everything())
```

```{r}
unemployment_df = 
  read_csv(file = 
      "./fivethirtyeight_datasets/unemployment.csv") 
```

```{r}
unemployment_data =
  pivot_longer(
    unemployment_df,
    Jan:Dec,
    names_to = "Month",
    values_to = "Unemployment Rate"
  )
```


